export const courses = [
  {
    id: 1,
    title: 'Traditional Bridal Makeup Mastery',
    instructor: 'Sarah Mitchell',
    level: 'Intermediate',
    duration: '6 weeks',
    students: 342,
    rating: 4.9,
    price: 199,
    image: '/images/1.jpg',
    category: 'Bridal',
    description: 'Master traditional bridal makeup with warm gold tones, perfect eyebrows, and timeless elegance for your special day.',
    lessons: 24,
  },
  {
    id: 2,
    title: 'Haldi Ceremony Makeup',
    instructor: 'Priya Sharma',
    level: 'Beginner',
    duration: '3 weeks',
    students: 428,
    rating: 4.95,
    price: 149,
    image: '/images/2.jpg',
    category: 'Ceremonial',
    description: 'Learn fresh, radiant makeup for Haldi ceremonies with golden undertones and natural glow.',
    lessons: 12,
  },
  {
    id: 3,
    title: 'Mehndi Makeup Magic',
    instructor: 'Jessica Rodriguez',
    level: 'Intermediate',
    duration: '4 weeks',
    students: 521,
    rating: 4.8,
    price: 169,
    image: '/images/3.jpg',
    category: 'Ceremonial',
    description: 'Create elegant and glowy mehndi makeup looks with sophisticated color palettes and modern techniques.',
    lessons: 16,
  },
  {
    id: 4,
    title: 'Evening & Party Makeup',
    instructor: 'Alex Thompson',
    level: 'Intermediate',
    duration: '5 weeks',
    students: 356,
    rating: 4.93,
    price: 179,
    image: '/images/4.jpg',
    category: 'Party',
    description: 'Master glamorous evening makeup with smokey eyes, bold lips, and showstopping looks for special events.',
    lessons: 20,
  },
  {
    id: 5,
    title: 'Bridal Elegance & Romance',
    instructor: 'Emma Williams',
    level: 'Advanced',
    duration: '7 weeks',
    students: 289,
    rating: 4.87,
    price: 229,
    image: '/images/5.jpg',
    category: 'Bridal',
    description: 'Timeless bridal looks with rose and mauve tones, perfect for creating your most elegant wedding day makeup.',
    lessons: 28,
  },
  {
    id: 6,
    title: 'Everyday Glam Made Simple',
    instructor: 'David Park',
    level: 'Beginner',
    duration: '3 weeks',
    students: 612,
    rating: 4.92,
    price: 99,
    image: '/images/6.jpg',
    category: 'Everyday',
    description: 'Soft, elegant everyday makeup with subtle glow and natural tones for work, brunch, and daily confidence.',
    lessons: 12,
  },
  {
    id: 7,
    title: 'Professional Makeup Application',
    instructor: 'Victoria Lee',
    level: 'Advanced',
    duration: '8 weeks',
    students: 267,
    rating: 4.96,
    price: 249,
    image: '/images/7.jpg',
    category: 'Professional',
    description: 'Learn professional makeup application techniques used by makeup artists at events and photoshoots.',
    lessons: 32,
  },
]

export const stats = [
  { number: '5000+', label: 'Students Worldwide' },
  { number: '50+', label: 'Professional Courses' },
  { number: '100%', label: 'Satisfaction Rate' },
  { number: '15+', label: 'Expert Instructors' },
]
